extends RefCounted
## Menu ve acilis ekrani metinleri. Dil beynin ayarindan (config.json
## "language"); beyin de ayni kodla konusuyor (langs.js).

const CODES := ["tr", "en", "es", "fr", "de", "pt", "ru", "ar", "hi", "ur", "id"]
const NAMES := ["Türkçe", "English", "Español", "Français", "Deutsch", "Português", "Русский", "العربية", "हिन्दी", "اردو", "Bahasa Indonesia"]

## anahtar -> CODES sirasiyla ceviriler
const T := {
	"caption": ["KEVİN · AYARLAR", "KEVIN · SETTINGS", "KEVIN · AJUSTES", "KEVIN · RÉGLAGES", "KEVIN · EINSTELLUNGEN", "KEVIN · CONFIGURAÇÕES", "КЕВИН · НАСТРОЙКИ", "كيفن · الإعدادات", "केविन · सेटिंग्स", "کیون · ترتیبات", "KEVIN · PENGATURAN"],
	"sub": ["masaüstü arkadaşın", "your desktop friend", "tu amigo de escritorio", "ton ami de bureau", "dein Desktop-Freund", "seu amigo de área de trabalho", "твой друг на рабочем столе", "صديقك على سطح المكتب", "तुम्हारा डेस्कटॉप दोस्त", "تمہارا ڈیسک ٹاپ دوست", "teman desktopmu"],
	"cat_sohbet": ["Sohbet", "Chat", "Chat", "Discussion", "Chat", "Conversa", "Чат", "المحادثة", "बातचीत", "گفتگو", "Obrolan"],
	"cat_karakter": ["Karakter", "Character", "Personaje", "Personnage", "Charakter", "Personagem", "Персонаж", "الشخصية", "किरदार", "کردار", "Karakter"],
	"cat_yapay_zeka": ["Yapay Zeka", "AI", "IA", "IA", "KI", "IA", "ИИ", "الذكاء الاصطناعي", "AI", "AI", "AI"],
	"cat_davranis": ["Davranış", "Behaviour", "Comportamiento", "Comportement", "Verhalten", "Comportamento", "Поведение", "السلوك", "व्यवहार", "رویہ", "Perilaku"],
	"cat_hakkinda": ["Hakkında", "About", "Acerca de", "À propos", "Über", "Sobre", "О программе", "حول", "परिचय", "تعارف", "Tentang"],
	"characters": ["KARAKTERLER", "CHARACTERS", "PERSONAJES", "PERSONNAGES", "CHARAKTERE", "PERSONAGENS", "ПЕРСОНАЖИ", "الشخصيات", "किरदार", "کردار", "KARAKTER"],
	"close": ["Kapat", "Close", "Cerrar", "Fermer", "Schließen", "Fechar", "Закрыть", "إغلاق", "बंद करें", "بند کریں", "Tutup"],
	"save": ["Kaydet", "Save", "Guardar", "Enregistrer", "Speichern", "Salvar", "Сохранить", "حفظ", "सहेजें", "محفوظ کریں", "Simpan"],
	"back": ["Geri", "Back", "Atrás", "Retour", "Zurück", "Voltar", "Назад", "رجوع", "वापस", "واپس", "Kembali"],
	"back_small": ["‹ geri", "‹ back", "‹ atrás", "‹ retour", "‹ zurück", "‹ voltar", "‹ назад", "‹ رجوع", "‹ वापस", "‹ واپس", "‹ kembali"],
	"rotate": ["Döndür", "Rotate", "Girar", "Tourner", "Drehen", "Girar", "Вращать", "تدوير", "घुमाएँ", "گھمائیں", "Putar"],
	"emote": ["Emote", "Emote", "Emote", "Emote", "Emote", "Emote", "Эмоция", "حركة", "इमोट", "ایموٹ", "Emote"],
	"reset": ["Sıfırla", "Reset", "Restablecer", "Réinitialiser", "Zurücksetzen", "Redefinir", "Сброс", "إعادة", "रीसेट", "ری سیٹ", "Atur ulang"],
	"drag_hint": ["karakteri sürükleyerek çevir", "drag the character to turn it", "arrastra para girar", "glisse pour tourner", "zum Drehen ziehen", "arraste para girar", "тяни, чтобы повернуть", "اسحب لتدوير الشخصية", "घुमाने के लिए खींचें", "گھمانے کے لیے کھینچیں", "seret untuk memutar"],
	"add_skin": ["Skin ekle (png)", "Add skin (png)", "Añadir skin (png)", "Ajouter un skin (png)", "Skin hinzufügen (png)", "Adicionar skin (png)", "Добавить скин (png)", "إضافة سكن (png)", "स्किन जोड़ें (png)", "اسکن شامل کریں (png)", "Tambah skin (png)"],
	"pick_skin": ["Skin seç", "Choose skin", "Elegir skin", "Choisir un skin", "Skin wählen", "Escolher skin", "Выбрать скин", "اختر سكن", "स्किन चुनें", "اسکن چنیں", "Pilih skin"],
	"chat_empty": ["Henüz konuşma yok. \"Kevin\" diye seslen ya da Kevin'e orta tıkla.", "No conversation yet. Say \"Kevin\" or middle-click him.", "Aún no hay conversación. Di \"Kevin\" o haz clic con la rueda.", "Pas encore de discussion. Dis « Kevin » ou clic molette sur lui.", "Noch kein Gespräch. Sag „Kevin“ oder klicke mit der Mitteltaste.", "Nenhuma conversa ainda. Diga \"Kevin\" ou clique com o botão do meio.", "Пока нет разговора. Скажи «Кевин» или нажми средней кнопкой.", "لا توجد محادثة بعد. قل \"كيفن\" أو انقر بالزر الأوسط.", "अभी कोई बातचीत नहीं। \"केविन\" बोलो या मिडल-क्लिक करो।", "ابھی کوئی گفتگو نہیں۔ \"کیون\" کہو یا مڈل کلک کرو۔", "Belum ada obrolan. Panggil \"Kevin\" atau klik tengah."],
	"you": ["SEN", "YOU", "TÚ", "TOI", "DU", "VOCÊ", "ТЫ", "أنت", "तुम", "تم", "KAMU"],
	"knows": ["KEVİN'İN BİLDİKLERİ", "WHAT KEVIN KNOWS", "LO QUE KEVIN SABE", "CE QUE KEVIN SAIT", "WAS KEVIN WEISS", "O QUE KEVIN SABE", "ЧТО ЗНАЕТ КЕВИН", "ما يعرفه كيفن", "केविन क्या जानता है", "کیون کیا جانتا ہے", "YANG KEVIN TAHU"],
	"knows_empty": ["Henüz bir şey öğrenmedi. Ona kendinden bahset, hatırlar; yanlış bir şey derse düzelt, öğrenir.", "Nothing yet. Tell him about yourself and he will remember; correct him and he learns.", "Nada aún. Háblale de ti y lo recordará; corrígelo y aprenderá.", "Rien pour l'instant. Parle-lui de toi, il s'en souviendra ; corrige-le, il apprendra.", "Noch nichts. Erzähl ihm von dir, er merkt es sich; korrigiere ihn, er lernt.", "Nada ainda. Fale de você e ele vai lembrar; corrija-o e ele aprende.", "Пока ничего. Расскажи о себе — он запомнит; поправь — он научится.", "لا شيء بعد. حدثه عن نفسك وسيتذكر، وصححه ليتعلم.", "अभी कुछ नहीं। उसे अपने बारे में बताओ, वह याद रखेगा; गलती सुधारो, वह सीखेगा।", "ابھی کچھ نہیں۔ اسے اپنے بارے میں بتاؤ، وہ یاد رکھے گا؛ غلطی درست کرو، وہ سیکھے گا۔", "Belum ada. Ceritakan tentang dirimu, dia akan ingat; koreksi dia, dia belajar."],
	"forget_all": ["Hepsini unut", "Forget everything", "Olvidar todo", "Tout oublier", "Alles vergessen", "Esquecer tudo", "Забыть всё", "انسَ كل شيء", "सब भूल जाओ", "سب بھول جاؤ", "Lupakan semua"],
	"forget_one": ["Bunu unut", "Forget this", "Olvidar esto", "Oublier ceci", "Das vergessen", "Esquecer isto", "Забыть это", "انسَ هذا", "इसे भूल जाओ", "یہ بھول جاؤ", "Lupakan ini"],
	"arm_model": ["Kol modeli", "Arm model", "Modelo de brazos", "Modèle des bras", "Armmodell", "Modelo dos braços", "Модель рук", "نموذج الذراع", "बाँह का मॉडल", "بازو کا ماڈل", "Model lengan"],
	"arm_classic": ["Klasik (4 px)", "Classic (4 px)", "Clásico (4 px)", "Classique (4 px)", "Klassisch (4 px)", "Clássico (4 px)", "Классика (4 px)", "كلاسيكي (4 px)", "क्लासिक (4 px)", "کلاسک (4 px)", "Klasik (4 px)"],
	"arm_slim": ["İnce (3 px)", "Slim (3 px)", "Delgado (3 px)", "Fin (3 px)", "Schmal (3 px)", "Fino (3 px)", "Тонкие (3 px)", "نحيف (3 px)", "पतला (3 px)", "پتلا (3 px)", "Ramping (3 px)"],
	"size": ["Boyut", "Size", "Tamaño", "Taille", "Größe", "Tamanho", "Размер", "الحجم", "आकार", "سائز", "Ukuran"],
	"size_hint": ["Kol modeli ve boyut Kaydet'e basınca uygulanır.", "Arm model and size apply when you press Save.", "El modelo y el tamaño se aplican al guardar.", "Le modèle et la taille s'appliquent à l'enregistrement.", "Armmodell und Größe gelten nach dem Speichern.", "Modelo e tamanho são aplicados ao salvar.", "Модель и размер применяются после сохранения.", "يُطبَّق النموذج والحجم عند الحفظ.", "मॉडल और आकार सहेजने पर लागू होते हैं।", "ماڈل اور سائز محفوظ کرنے پر لاگو ہوں گے۔", "Model dan ukuran berlaku saat disimpan."],
	"walk_speed": ["Yürüme hızı", "Walking speed", "Velocidad al caminar", "Vitesse de marche", "Gehtempo", "Velocidade de caminhada", "Скорость ходьбы", "سرعة المشي", "चलने की गति", "چلنے کی رفتار", "Kecepatan jalan"],
	"speech_rate": ["Konuşma hızı", "Speaking speed", "Velocidad al hablar", "Vitesse de parole", "Sprechtempo", "Velocidade da fala", "Скорость речи", "سرعة الكلام", "बोलने की गति", "بولنے کی رفتار", "Kecepatan bicara"],
	"skin_hint": ["Skin: ana menüdeki Karakterler'den seç, + ile kendi png'ni ekle (64x64 Minecraft skin).", "Skin: pick one under Characters on the main page, or add your own png with + (64x64 Minecraft skin).", "Skin: elige en Personajes o añade tu png con + (skin de Minecraft 64x64).", "Skin : choisis dans Personnages ou ajoute ton png avec + (skin Minecraft 64x64).", "Skin: unter Charaktere wählen oder eigenes png mit + hinzufügen (64x64 Minecraft-Skin).", "Skin: escolha em Personagens ou adicione seu png com + (skin Minecraft 64x64).", "Скин: выбери в «Персонажах» или добавь свой png через + (скин Minecraft 64x64).", "السكن: اختر من الشخصيات أو أضف ملف png عبر + (سكن ماينكرافت 64x64).", "स्किन: किरदारों में से चुनो या + से अपना png जोड़ो (64x64 Minecraft स्किन)।", "اسکن: کرداروں میں سے چنو یا + سے اپنا png شامل کرو (64x64 Minecraft اسکن)۔", "Skin: pilih di Karakter atau tambah png sendiri dengan + (skin Minecraft 64x64)."],
	"language": ["Dil", "Language", "Idioma", "Langue", "Sprache", "Idioma", "Язык", "اللغة", "भाषा", "زبان", "Bahasa"],
	"language_hint": ["Menü, konuşma ve ses bu dilde olur. Ses ilk seçimde indirilir (yaklaşık 60 MB).", "Menu, speech and voice use this language. The voice downloads the first time (about 60 MB).", "Menú, habla y voz en este idioma. La voz se descarga la primera vez (unos 60 MB).", "Menu, parole et voix dans cette langue. La voix se télécharge la première fois (environ 60 Mo).", "Menü, Sprache und Stimme in dieser Sprache. Die Stimme wird beim ersten Mal geladen (ca. 60 MB).", "Menu, fala e voz neste idioma. A voz é baixada na primeira vez (cerca de 60 MB).", "Меню, речь и голос на этом языке. Голос скачивается при первом выборе (около 60 МБ).", "القائمة والكلام والصوت بهذه اللغة. يُنزَّل الصوت أول مرة (حوالي 60 ميغابايت).", "मेनू, बोली और आवाज़ इसी भाषा में। आवाज़ पहली बार डाउनलोड होती है (लगभग 60 MB)।", "مینو، بات چیت اور آواز اسی زبان میں۔ آواز پہلی بار ڈاؤن لوڈ ہوتی ہے (تقریباً 60 MB)۔", "Menu, ucapan dan suara memakai bahasa ini. Suara diunduh pertama kali (sekitar 60 MB)."],
	"mode": ["Çalışma şekli", "Mode", "Modo", "Mode", "Modus", "Modo", "Режим", "الوضع", "मोड", "موڈ", "Mode"],
	"mode_cloud": ["Bulut (API)", "Cloud (API)", "Nube (API)", "Cloud (API)", "Cloud (API)", "Nuvem (API)", "Облако (API)", "سحابي (API)", "क्लाउड (API)", "کلاؤڈ (API)", "Cloud (API)"],
	"mode_local": ["Yerel (Ollama)", "Local (Ollama)", "Local (Ollama)", "Local (Ollama)", "Lokal (Ollama)", "Local (Ollama)", "Локально (Ollama)", "محلي (Ollama)", "लोकल (Ollama)", "لوکل (Ollama)", "Lokal (Ollama)"],
	"mode_hint": ["Bulut: hızlı, internet ve kendi anahtarın gerekir. Yerel: bilgisayarında çalışır, Ollama kurulu olmalı.", "Cloud: fast, needs internet and your own key. Local: runs on your computer, needs Ollama.", "Nube: rápida, necesita internet y tu propia clave. Local: funciona en tu equipo, necesita Ollama.", "Cloud : rapide, il faut internet et ta propre clé. Local : tourne sur ton ordinateur, il faut Ollama.", "Cloud: schnell, braucht Internet und eigenen Schlüssel. Lokal: läuft auf deinem Rechner, braucht Ollama.", "Nuvem: rápida, precisa de internet e da sua chave. Local: roda no seu computador, precisa do Ollama.", "Облако: быстро, нужен интернет и свой ключ. Локально: работает на твоём компьютере, нужен Ollama.", "السحابي: سريع ويحتاج إنترنت ومفتاحك الخاص. المحلي: يعمل على جهازك ويحتاج Ollama.", "क्लाउड: तेज़, इंटरनेट और अपनी कुंजी चाहिए। लोकल: तुम्हारे कंप्यूटर पर चलता है, Ollama चाहिए।", "کلاؤڈ: تیز، انٹرنیٹ اور اپنی کلید چاہیے۔ لوکل: تمہارے کمپیوٹر پر چلتا ہے، Ollama چاہیے۔", "Cloud: cepat, butuh internet dan kunci sendiri. Lokal: berjalan di komputermu, butuh Ollama."],
	"provider": ["Sağlayıcı", "Provider", "Proveedor", "Fournisseur", "Anbieter", "Provedor", "Провайдер", "المزوّد", "प्रदाता", "فراہم کنندہ", "Penyedia"],
	"model": ["Model", "Model", "Modelo", "Modèle", "Modell", "Modelo", "Модель", "النموذج", "मॉडल", "ماڈل", "Model"],
	"model_hint": ["Boş bırakırsan sağlayıcının varsayılanı.", "Leave empty for the provider's default.", "Vacío: el predeterminado del proveedor.", "Vide : celui par défaut du fournisseur.", "Leer: Standard des Anbieters.", "Vazio: padrão do provedor.", "Пусто — модель по умолчанию.", "اتركه فارغا لاستخدام الافتراضي.", "खाली छोड़ो तो डिफ़ॉल्ट।", "خالی چھوڑو تو ڈیفالٹ۔", "Kosongkan untuk bawaan penyedia."],
	"api_key": ["API anahtarı", "API key", "Clave de API", "Clé API", "API-Schlüssel", "Chave de API", "API-ключ", "مفتاح API", "API कुंजी", "API کلید", "Kunci API"],
	"key_saved": ["•••••••• kayıtlı (değiştirmek için yaz)", "•••••••• saved (type to change)", "•••••••• guardada (escribe para cambiar)", "•••••••• enregistrée (tape pour changer)", "•••••••• gespeichert (zum Ändern tippen)", "•••••••• salva (digite para mudar)", "•••••••• сохранён (введи, чтобы сменить)", "•••••••• محفوظ (اكتب للتغيير)", "•••••••• सहेजी गई (बदलने के लिए लिखो)", "•••••••• محفوظ (بدلنے کے لیے لکھو)", "•••••••• tersimpan (ketik untuk mengganti)"],
	"key_new": ["Kendi API anahtarını yapıştır", "Paste your own API key", "Pega tu propia clave", "Colle ta propre clé", "Eigenen Schlüssel einfügen", "Cole sua própria chave", "Вставь свой ключ", "الصق مفتاحك الخاص", "अपनी कुंजी पेस्ट करो", "اپنی کلید پیسٹ کرو", "Tempel kunci milikmu"],
	"key_hint": ["Sadece bu bilgisayarda saklanır. Herkes kendi anahtarını kullanır.", "Stored only on this computer. Everyone uses their own key.", "Solo se guarda en este equipo. Cada uno usa su clave.", "Stockée uniquement sur cet ordinateur. Chacun utilise sa clé.", "Nur auf diesem Rechner gespeichert. Jeder nutzt seinen eigenen.", "Fica só neste computador. Cada um usa a sua.", "Хранится только на этом компьютере. У каждого свой ключ.", "يُحفظ على هذا الجهاز فقط. كل شخص يستخدم مفتاحه.", "सिर्फ़ इसी कंप्यूटर पर रहती है। हर कोई अपनी कुंजी लगाता है।", "صرف اسی کمپیوٹر پر رہتی ہے۔ ہر کوئی اپنی کلید لگاتا ہے۔", "Hanya disimpan di komputer ini. Tiap orang memakai kuncinya sendiri."],
	"no_key": ["Kevin'in konuşabilmesi için kendi API anahtarını gir ya da Yerel (Ollama) seç.", "To let Kevin talk, enter your own API key or choose Local (Ollama).", "Para que Kevin hable, pon tu clave de API o elige Local (Ollama).", "Pour que Kevin parle, entre ta clé API ou choisis Local (Ollama).", "Damit Kevin spricht: eigenen API-Schlüssel eingeben oder Lokal (Ollama) wählen.", "Para Kevin falar, coloque sua chave de API ou escolha Local (Ollama).", "Чтобы Кевин заговорил, введи свой API-ключ или выбери «Локально (Ollama)».", "ليتكلم كيفن، أدخل مفتاح API الخاص بك أو اختر محلي (Ollama).", "केविन को बोलने के लिए अपनी API कुंजी डालो या लोकल (Ollama) चुनो।", "کیون کو بولنے کے لیے اپنی API کلید ڈالو یا لوکل (Ollama) چنو۔", "Agar Kevin bisa bicara, masukkan kunci API-mu atau pilih Lokal (Ollama)."],
	"name": ["İsim", "Name", "Nombre", "Nom", "Name", "Nome", "Имя", "الاسم", "नाम", "نام", "Nama"],
	"name_hint": ["Bu isimle seslenince uyanır.", "He wakes up when you call this name.", "Se despierta al decir este nombre.", "Il se réveille quand tu dis ce nom.", "Er wacht auf, wenn du diesen Namen rufst.", "Ele acorda quando você diz este nome.", "Просыпается, когда зовёшь по имени.", "يستيقظ عندما تناديه بهذا الاسم.", "इस नाम से पुकारो तो जागता है।", "اس نام سے پکارو تو جاگتا ہے۔", "Dia bangun saat nama ini dipanggil."],
	"nicknames": ["Lakaplar", "Nicknames", "Apodos", "Surnoms", "Spitznamen", "Apelidos", "Прозвища", "الألقاب", "उपनाम", "عرفی نام", "Nama panggilan"],
	"nick_hint": ["Virgülle ayır.", "Separate with commas.", "Separa con comas.", "Sépare par des virgules.", "Mit Kommas trennen.", "Separe com vírgulas.", "Через запятую.", "افصل بفواصل.", "कॉमा से अलग करो।", "کاما سے الگ کرو۔", "Pisahkan dengan koma."],
	"hands_free": ["Eller serbest dinleme", "Hands-free listening", "Escucha manos libres", "Écoute mains libres", "Freihändig zuhören", "Escuta mãos-livres", "Слушать без рук", "استماع دون استخدام اليدين", "हैंड्स-फ़्री सुनना", "ہینڈز فری سننا", "Mendengar tanpa tangan"],
	"session": ["Sohbet süresi", "Conversation window", "Duración de la charla", "Durée d'écoute", "Gesprächsdauer", "Duração da conversa", "Время разговора", "مدة المحادثة", "बातचीत का समय", "گفتگو کا وقت", "Durasi obrolan"],
	"session_hint": ["Adını söyledikten sonra ne kadar dinlesin.", "How long he keeps listening after his name.", "Cuánto escucha tras oír su nombre.", "Combien de temps il écoute après son nom.", "Wie lange er nach seinem Namen zuhört.", "Quanto tempo ouve depois do nome.", "Сколько слушать после имени.", "كم يستمع بعد سماع اسمه.", "नाम के बाद कितनी देर सुने।", "نام کے بعد کتنی دیر سنے۔", "Berapa lama mendengar setelah namanya."],
	"sec": ["sn", "s", "s", "s", "s", "s", "с", "ث", "से", "سیکنڈ", "dtk"],
	"camera": ["Kamera", "Camera", "Cámara", "Caméra", "Kamera", "Câmera", "Камера", "الكاميرا", "कैमरा", "کیمرا", "Kamera"],
	"camera_on": ["Kameraya bakabilsin", "Allow camera", "Permitir la cámara", "Autoriser la caméra", "Kamera erlauben", "Permitir a câmera", "Разрешить камеру", "السماح بالكاميرا", "कैमरा चालू रहने दो", "کیمرا کی اجازت", "Izinkan kamera"],
	"camera_greet": ["Seslenince bakıp tanısın", "Look and recognise when called", "Mirar y reconocer al llamarlo", "Regarder et reconnaître à l'appel", "Beim Rufen schauen und erkennen", "Olhar e reconhecer ao chamar", "Смотреть и узнавать при зове", "ينظر ويتعرف عند مناداته", "पुकारने पर देखे और पहचाने", "پکارنے پر دیکھے اور پہچانے", "Melihat dan mengenali saat dipanggil"],
	"camera_hint": ["Kamera sadece sen isteyince (\"bana bak\", \"bu ne\") ya da seslenince açılır; görüntü saklanmaz. Tanıması için kameraya bakıp \"bu benim, beni hatırla\" de.", "The camera only opens when you ask (\"look at me\", \"what is this\") or call him; frames are not kept. To be recognised, look at it and say \"this is me, remember me\".", "La cámara solo se abre si lo pides o lo llamas; no se guardan imágenes. Para que te reconozca, mira y di \"soy yo, recuérdame\".", "La caméra ne s'ouvre que si tu le demandes ou l'appelles ; rien n'est gardé. Pour être reconnu, regarde-la et dis « c'est moi, souviens-toi ».", "Die Kamera geht nur an, wenn du fragst oder ihn rufst; Bilder werden nicht gespeichert. Zum Erkennen hineinschauen und „das bin ich, merk dir mich“ sagen.", "A câmera só abre quando você pede ou chama; nada é guardado. Para ser reconhecido, olhe e diga \"sou eu, lembre de mim\".", "Камера включается только по просьбе или зову; кадры не сохраняются. Чтобы он узнавал тебя, посмотри в камеру и скажи «это я, запомни меня».", "تعمل الكاميرا فقط عندما تطلب أو تناديه، ولا تُحفظ الصور. ليتعرف عليك انظر إليها وقل \"هذا أنا، تذكرني\".", "कैमरा सिर्फ़ तुम्हारे कहने या पुकारने पर खुलता है; तस्वीरें नहीं रखी जातीं। पहचान के लिए कैमरे में देखकर कहो \"यह मैं हूँ, मुझे याद रखो\"।", "کیمرا صرف تمہارے کہنے یا پکارنے پر کھلتا ہے؛ تصویریں نہیں رکھی جاتیں۔ پہچان کے لیے کیمرے میں دیکھ کر کہو \"یہ میں ہوں، مجھے یاد رکھو\"۔", "Kamera hanya menyala saat kamu minta atau memanggilnya; gambar tidak disimpan. Agar dikenali, lihat kamera dan bilang \"ini aku, ingat aku\"."],
	"faces": ["Tanıdığı yüzler", "Known faces", "Caras conocidas", "Visages connus", "Bekannte Gesichter", "Rostos conhecidos", "Знакомые лица", "الوجوه المعروفة", "पहचाने चेहरे", "پہچانے چہرے", "Wajah dikenal"],
	"faces_none": ["henüz yok", "none yet", "ninguna aún", "aucun pour l'instant", "noch keine", "nenhum ainda", "пока нет", "لا يوجد بعد", "अभी कोई नहीं", "ابھی کوئی نہیں", "belum ada"],
	"forget_faces": ["Yüzleri unut", "Forget faces", "Olvidar caras", "Oublier les visages", "Gesichter vergessen", "Esquecer rostos", "Забыть лица", "انسَ الوجوه", "चेहरे भूल जाओ", "چہرے بھول جاؤ", "Lupakan wajah"],
	"persona": ["Kişilik", "Personality", "Personalidad", "Personnalité", "Persönlichkeit", "Personalidade", "Характер", "الشخصية", "व्यक्तित्व", "شخصیت", "Kepribadian"],
	"persona_ph": ["Boş: varsayılan kişilik (esprili, samimi).", "Empty: default personality (witty, friendly).", "Vacío: personalidad por defecto (ingenioso, cercano).", "Vide : personnalité par défaut (drôle, sympa).", "Leer: Standard (witzig, herzlich).", "Vazio: personalidade padrão (divertido, amigável).", "Пусто: характер по умолчанию (остроумный, дружелюбный).", "فارغ: الشخصية الافتراضية (مرح وودود).", "खाली: डिफ़ॉल्ट व्यक्तित्व (मज़ाकिया, दोस्ताना)।", "خالی: ڈیفالٹ شخصیت (مزاحیہ، دوستانہ)۔", "Kosong: kepribadian bawaan (lucu, ramah)."],
	"walk_freq": ["Yürüme sıklığı", "How often he walks", "Frecuencia al caminar", "Fréquence de marche", "Wie oft er läuft", "Frequência de caminhada", "Как часто ходит", "كم مرة يمشي", "कितनी बार चले", "کتنی بار چلے", "Seberapa sering berjalan"],
	"emote_freq": ["Kendi kendine hareket", "Idle movements", "Movimientos espontáneos", "Mouvements spontanés", "Eigene Bewegungen", "Movimentos espontâneos", "Движения сам по себе", "حركات تلقائية", "अपने आप हरकतें", "خود سے حرکتیں", "Gerakan spontan"],
	"look": ["Fareyi arada merak edip baksın", "Glance at the mouse now and then", "Mirar el ratón de vez en cuando", "Regarder la souris de temps en temps", "Ab und zu zur Maus schauen", "Olhar o mouse às vezes", "Иногда смотреть на мышь", "ينظر إلى الفأرة أحيانا", "कभी-कभी माउस को देखे", "کبھی کبھی ماؤس کو دیکھے", "Sesekali melirik mouse"],
	"wall_sit": ["Kenara yaslanıp otursun", "Sit leaning on the edge", "Sentarse apoyado en el borde", "S'asseoir adossé au bord", "Am Rand anlehnen und sitzen", "Sentar encostado na borda", "Сидеть, прислонившись к краю", "يجلس مستندا إلى الحافة", "किनारे से टेक लगाकर बैठे", "کنارے سے ٹیک لگا کر بیٹھے", "Duduk bersandar di tepi"],
	"fun": ["Arada eğlenceli hareketler", "Playful moves now and then", "Movimientos divertidos a veces", "Gestes amusants parfois", "Ab und zu lustige Moves", "Movimentos divertidos às vezes", "Иногда весёлые движения", "حركات مرحة أحيانا", "कभी-कभी मज़ेदार हरकतें", "کبھی کبھی مزے کی حرکتیں", "Sesekali gerakan lucu"],
	"dance": ["Şarkı çalınca dans etsin", "Dance when a song plays", "Bailar cuando suena música", "Danser quand une chanson joue", "Tanzen, wenn Musik läuft", "Dançar quando tocar música", "Танцевать под песню", "يرقص عند تشغيل أغنية", "गाना बजे तो नाचे", "گانا چلے تو ناچے", "Menari saat lagu diputar"],
	"dance_hint": ["Sadece şarkıda; video izlerken dans etmez.", "Only for songs, not while you watch videos.", "Solo con canciones, no con vídeos.", "Seulement pour les chansons, pas les vidéos.", "Nur bei Liedern, nicht bei Videos.", "Só com músicas, não com vídeos.", "Только под песни, не под видео.", "مع الأغاني فقط، لا مع الفيديو.", "सिर्फ़ गानों पर, वीडियो पर नहीं।", "صرف گانوں پر، ویڈیو پر نہیں۔", "Hanya untuk lagu, bukan video."],
	"mood": ["Duygularını hareketle göstersin", "Show feelings with gestures", "Mostrar emociones con gestos", "Montrer ses émotions par des gestes", "Gefühle mit Gesten zeigen", "Mostrar emoções com gestos", "Показывать эмоции жестами", "يعبّر عن مشاعره بالحركات", "भावनाएँ हरकतों से दिखाए", "جذبات حرکتوں سے دکھائے", "Tunjukkan perasaan dengan gerakan"],
	"night": ["Gece uykulu olsun", "Sleepy at night", "Con sueño de noche", "Somnolent la nuit", "Nachts müde", "Com sono à noite", "Сонный ночью", "نعسان ليلا", "रात में ऊँघे", "رات کو اونگھے", "Mengantuk di malam hari"],
	"sleep_after": ["Boşta kalınca uyusun", "Fall asleep when idle", "Dormirse en reposo", "S'endormir au repos", "Bei Ruhe einschlafen", "Dormir quando ocioso", "Засыпать без дела", "ينام عند الخمول", "खाली रहे तो सो जाए", "فارغ رہے تو سو جائے", "Tidur saat menganggur"],
	"min": ["dk", "min", "min", "min", "Min.", "min", "мин", "د", "मिनट", "منٹ", "mnt"],
	"off": ["kapalı", "off", "no", "non", "aus", "não", "выкл", "إيقاف", "बंद", "بند", "mati"],
	"about_text": ["Masaüstünde yaşayan, konuşan, seni tanıyan ve bilgisayarını kullanabilen yapay zeka arkadaşı.", "An AI friend who lives on your desktop, talks, gets to know you and can use your computer.", "Un amigo con IA que vive en tu escritorio, habla, te conoce y puede usar tu ordenador.", "Un ami IA qui vit sur ton bureau, parle, apprend à te connaître et sait utiliser ton ordinateur.", "Ein KI-Freund auf deinem Desktop, der spricht, dich kennenlernt und deinen Rechner bedienen kann.", "Um amigo com IA que vive na sua área de trabalho, conversa, conhece você e usa seu computador.", "ИИ-друг на твоём рабочем столе: разговаривает, узнаёт тебя и умеет пользоваться компьютером.", "صديق بالذكاء الاصطناعي يعيش على سطح مكتبك، يتكلم ويتعرف عليك ويستطيع استخدام حاسوبك.", "तुम्हारे डेस्कटॉप पर रहने वाला AI दोस्त, जो बात करता है, तुम्हें जानता है और कंप्यूटर चला सकता है।", "تمہارے ڈیسک ٹاپ پر رہنے والا AI دوست جو بات کرتا ہے، تمہیں جانتا ہے اور کمپیوٹر چلا سکتا ہے۔", "Teman AI yang tinggal di desktop, bisa bicara, mengenalmu, dan memakai komputermu."],
	"animations": ["Animasyonlar", "Animations", "Animaciones", "Animations", "Animationen", "Animações", "Анимации", "الرسوم المتحركة", "एनिमेशन", "اینیمیشن", "Animasi"],
	"usage": ["Kullanım", "How to use", "Uso", "Utilisation", "Bedienung", "Como usar", "Как пользоваться", "الاستخدام", "उपयोग", "استعمال", "Cara pakai"],
	"usage_text": ["Menü: karaktere sağ tık. Karakteri sürükle: döndür. Esc: kapat. Orta tık: Kevin'i uyandır.", "Menu: right-click the character. Drag to turn him. Esc: close. Middle-click: wake Kevin.", "Menú: clic derecho. Arrastra para girarlo. Esc: cerrar. Clic central: despertar a Kevin.", "Menu : clic droit. Glisse pour le tourner. Échap : fermer. Clic molette : réveiller Kevin.", "Menü: Rechtsklick. Ziehen zum Drehen. Esc: schließen. Mittelklick: Kevin wecken.", "Menu: clique direito. Arraste para girar. Esc: fechar. Clique do meio: acordar o Kevin.", "Меню: правый клик. Тяни, чтобы повернуть. Esc: закрыть. Средний клик: разбудить Кевина.", "القائمة: نقر بالزر الأيمن. اسحب للتدوير. Esc: إغلاق. النقر الأوسط: إيقاظ كيفن.", "मेनू: राइट-क्लिक। घुमाने के लिए खींचो। Esc: बंद। मिडल-क्लिक: केविन को जगाओ।", "مینو: رائٹ کلک۔ گھمانے کے لیے کھینچو۔ Esc: بند۔ مڈل کلک: کیون کو جگاؤ۔", "Menu: klik kanan. Seret untuk memutar. Esc: tutup. Klik tengah: bangunkan Kevin."],
	"replay_splash": ["Açılış ekranını oynat", "Replay intro", "Ver la intro", "Revoir l'intro", "Intro abspielen", "Ver a abertura", "Показать заставку", "إعادة المقدمة", "शुरुआती स्क्रीन चलाओ", "آغاز اسکرین چلاؤ", "Putar intro"],
	"splash_hello": ["SELAM, BEN", "HI, I'M", "HOLA, SOY", "SALUT, C'EST", "HALLO, ICH BIN", "OI, EU SOU", "ПРИВЕТ, Я", "مرحبا، أنا", "नमस्ते, मैं", "سلام، میں", "HALO, AKU"],
	"splash_your": ["SENİN", "YOUR", "TU", "TON", "DEIN", "SEU", "ТВОЙ", "", "तुम्हारा", "تمہارا", ""],
	"splash_friend": ["ARKADAŞIN", "FRIEND", "AMIGO", "AMI", "FREUND", "AMIGO", "ДРУГ", "صديقك", "दोस्त", "دوست", "TEMANMU"],
	"splash_say": ["Adımı söyle,|gerisini ben|hallederim", "Say my name,|I'll handle|the rest", "Di mi nombre,|yo me encargo|del resto", "Dis mon nom,|je m'occupe|du reste", "Sag meinen|Namen, den Rest|mach ich", "Diga meu nome,|eu cuido|do resto", "Скажи моё имя,|остальное|сделаю я", "قل اسمي|وأنا أتكفل|بالباقي", "मेरा नाम लो,|बाकी मैं|संभाल लूँगा", "میرا نام لو،|باقی میں|سنبھال لوں گا", "Sebut namaku,|sisanya|aku urus"],
	"splash_loading": ["Hazırlanıyorum...", "Getting ready...", "Preparándome...", "Je me prépare...", "Mache mich bereit...", "Me preparando...", "Готовлюсь...", "أستعد...", "तैयार हो रहा हूँ...", "تیار ہو رہا ہوں...", "Bersiap..."],
	"splash_ready": ["Hazırım!", "Ready!", "¡Listo!", "Prêt !", "Bereit!", "Pronto!", "Готов!", "جاهز!", "तैयार!", "تیار!", "Siap!"],
}


static func code_of(cfg: Dictionary) -> String:
	var raw := str(cfg.get("language", "tr")).to_lower()
	if raw in CODES:
		return raw
	if raw.begins_with("tur"):
		return "tr"
	return raw.substr(0, 2) if raw.substr(0, 2) in CODES else "tr"


static func get_text(key: String, code: String) -> String:
	if not T.has(key):
		return key
	var i := CODES.find(code)
	return T[key][i if i >= 0 else 0]
